### PR TITLE
709 parse amqp headers as strings

### LINKED ISSUE #709: [RabbitMQ consumer] message headers not parsed correctly for strings
__Describe the Bug__

Parsing string headers for RabbitMQ messages does not work correctly

__Steps to Reproduce__

1. send a message with string header 
image

2. observe message in Operate

*Problem*
the header value is displayed as byte
```
				"HEADER_STRING": {
					"bytes": "aGVsbG8=",
					"stream": {}
				},
```

__Expected Behavior__

__Environment__

- Connctor version: [0.20]

### PR DESCRIPTION
**Pull request by chillleader**
## Description

1. Adds a custom DTO for RabbitMQ message properties to handle header deserialization properly (byte arrays should be handled as strings)
1. Also handles the potential NPE in `RabbitMqConsumer` when correlation result is null

## Related issues

closes #709

### CODE REVIEW

File: connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/model/RabbitMqMessageProperties.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+      return longString.toString();
+    } else if (value instanceof List<?> list) {
+      return list.stream().map(RabbitMqMessageProperties::handleHeaderValue).toList();
+    } else {
+      // long, boolean are represented as their respective types, so we don't need to do anything
+      LOG.debug(
+          "Unhandled header value type: {}. Original value will be returned", value.getClass());
+      return value;
+    }
+  }
```
Comment (sbuettner) [inline connectors/rabbitmq/src/main/java/io/camunda/connector/rabbitmq/inbound/model/RabbitMqMessageProperties.java:80]: We could move it outside of the record as a static utility function for easier testability: 
```
AMQPPropertySupport.toProperties(AMQP.BasicProperties properties)
```

**Review by sbuettner — APPROVED** [review]
Looks good to me. Just a minor refactoring idea.

**Review by sbuettner — APPROVED** [review]
